### ISSUE TITLE
Membuat Mockup

### ISSUE THREAD

**Issue by nurliyanfaris** [nurliyanfaris/RPL-BEASA#1]
Membuat design halaman login, register, home, dan user profile

**Comment by gildascato** [comment]
Link Canva
https://www.canva.com/design/DAE73sKpkp8/ZgRNCR3OCiU8elbj17W2cw/edit?utm_content=DAE73sKpkp8&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by gildascato** [comment]
Link Figma
https://www.figma.com/file/LdDcxXljmhXB4REktNVXQV/Untitled?node-id=0%3A1

**Comment by ramizqudamah** [comment]
Link Figma
https://www.figma.com/file/LdDcxXljmhXB4REktNVXQV/Untitled?node-id=0%3A1

**Comment by ariqikbard** [comment]
Ppk

**Comment by ariqikbard** [comment]
Link Mockup
https://www.figma.com/file/LdDcxXljmhXB4REktNVXQV/Bea%7CSa?node-id=35%3A488
